$(function(){
    $('.menu_btnm').click(function(){
        $('.menusm').slideToggle('slow')
        $('.menus_strm').slideToggle('slow')
    })
    $('.arrow1m').click(function(){
        $('.picturesm').eq(0).removeClass('.display_none')
    })
    $('.exhibitionsm').click(function(){
        $('.artm').addClass('display_none')
        $('.art2m').addClass('display_none')
        $('.eventm').addClass('display_none')
        $('.event2m').addClass('display_none')
        $('.exhibitionm').addClass('display_none')
        $('.exhibition2m').addClass('display_none')
        $('.main_bgm').addClass('display_none')
        $('.main_bg1m').addClass('display_none')
        $('.art3m').removeClass('display_none')
        $('.event3m').removeClass('display_none')
        $('.exhibition3m').removeClass('display_none')
        $('.main_bg2m').removeClass('display_none')
        $('.all_imgm').vegas('jump', 2);
        $('.all_imgm').vegas('pause');
        $('.art2m').animate({opacity:0})
        $('.event2m').animate({opacity:0})
        $('.exhibition2m').animate({opacity:0})
        $('.artm').animate({opacity:0})
        $('.eventm').animate({opacity:0})
        $('.exhibitionm').animate({opacity:0})
        $('.art3m').animate({opacity:1},3000)
        $('.event3m').animate({opacity:1},3000)
        $('.exhibition3m').animate({opacity:1},3000)
    })
    $('.artsm').click(function(){
        $('.art2m').addClass('display_none')
        $('.art3m').addClass('display_none')
        $('.event2m').addClass('display_none')
        $('.event3m').addClass('display_none')
        $('.exhibition2m').addClass('display_none')
        $('.exhibition3m').addClass('display_none')
        $('.main_bgm').addClass('display_none')
        $('.main_bg2m').addClass('display_none')
        $('.main_bg1m').removeClass('display_none')
        $('.artm').removeClass('display_none')
        $('.eventm').removeClass('display_none')
        $('.exhibitionm').removeClass('display_none')
        $('.all_imgm').vegas('jump', 1);
        $('.all_imgm').vegas('pause');
        $('.art2m').animate({opacity:0})
        $('.event2m').animate({opacity:0})
        $('.exhibition2m').animate({opacity:0})
        $('.artm').animate({opacity:1},3000)
        $('.eventm').animate({opacity:1},3000)
        $('.exhibitionm').animate({opacity:1},3000)
        $('.art3m').animate({opacity:0})
        $('.event3m').animate({opacity:0})
        $('.exhibition3m').animate({opacity:0})
    })
    $('.eventsm').click(function(){
        $('.artm').addClass('display_none')
        $('.art3m').addClass('display_none')
        $('.eventm').addClass('display_none')
        $('.event3m').addClass('display_none')
        $('.exhibitionm').addClass('display_none')
        $('.exhibition3m').addClass('display_none')
        $('.main_bgm').removeClass('display_none')
        $('.main_bg2m').addClass('display_none')
        $('.main_bg1m').addClass('display_none')
        $('.art2m').removeClass('display_none')
        $('.event2m').removeClass('display_none')
        $('.exhibition2m').removeClass('display_none')
        $('.all_imgm').vegas('jump', 0);
        $('.all_imgm').vegas('pause');
        $('.art2m').animate({opacity:1},3000)
        $('.event2m').animate({opacity:1},3000)
        $('.exhibition2m').animate({opacity:1},3000)
        $('.artm').animate({opacity:0})
        $('.eventm').animate({opacity:0})
        $('.exhibitionm').animate({opacity:0})
        $('.art3m').animate({opacity:0})
        $('.event3m').animate({opacity:0})
        $('.exhibition3m').animate({opacity:0})
    })
    $('.all_imgm').vegas({
        loop:false,
        animationDuration:2000,
        transitionDuration:500,
        slides: [
                { src: './image/앱배경4.png' },
                { src: './image/앱배경2.png' },
                { src: './image/앱배경1.png' }
        ],
        animation: 'kenburns'
    });
    $('.all_imgm').vegas('pause');
})